name: deploy docs

on:
  push:
    branches:
      - lab1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install mkdocs mkdocs-material
      - run: mkdocs gh-deploy --force
        working-directory: students/K3339/Telegin_Daniil/Lab1/reports
